cheapdrive_web/cheapdrive_website/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',
    include("entry.urls")),
    path('admin/', admin.site.urls),
    path('', include('refill.urls', namespace='refill')),
    #path("refill/",
    #include("refill.urls")),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cheapdrive_web/entry/urls.py
from django.urls import path
from . import views


app_name = 'entry' 

urlpatterns = [
    path("", views.visit, name="visit"),
    path('login/', views.login_view, name='login'),
    
    path('guest/', views.guest_access, name='guest_access'),
    path('register/', views.register, name='register'),
    path('logged/', views.logged_view, name='logged'),
    path('history/', views.trip_history_view, name='trip_history'), 
    
    path('vehicles/', views.user_vehicles_view, name='user_vehicles'),
    path('logout/',views.logout_view,name='logout')
]

cheapdrive_web/refill/urls.py
from django.urls import path
from . import views 

app_name = 'refill' 
urlpatterns = [
     path('results/', views.results, name='results'),
    #for using idspath('load_data/<int:vehicle_id>/<int:trip_id>/', views.load_data, name='load_data'),
    path('load_data/', views.load_data, name='load_data'),
    # ... other URL patterns ...
    path('refill_management/', views.refill_management, name='refill_management'),
    path('choose_option/', views.choose_option, name='choose_option'),
    path('refill_amount/', views.process_fuel_amount, name='refill_amount'),]

cheapdrive_web/entry/models.py
from django.db import models
from django.contrib.gis.db import models as gis_models
from django.contrib.auth.models import AbstractUser,UserManager
from django.db.models.fields import related

class User(AbstractUser):
    """
    Custom User model that extends Django's AbstractUser.
    
    This model enforces unique email addresses, and customizes the groups and permissions
    through unique related names for better flexibility in querying and managing users.
    It uses Django's built-in UserManager for handling user-related queries and operations.
    """
    email = models.EmailField(unique=True)
    groups = models.ManyToManyField(
        "auth.Group",
        related_name="custom_user_groups"  # Unique related_name.
    )
    user_permissions = models.ManyToManyField(
        "auth.Permission",
        related_name="custom_user_permissions"  # Unique related_name.
    )
    objects = UserManager()


class StationPrices(models.Model):
    """
    Model representing fuel station prices for different fuel types.
    
    This model holds pricing information for different fuel types (e.g., Diesel, LPG, PB95, PB98) 
    at various fuel stations. Each price field is represented as a decimal value and stored with 
    the associated currency (defaulted to PLN). The model is linked to specific brands through 
    the `BrandChoices` enumeration.
    """

    class BrandChoices(models.TextChoices):
        """
        Enumeration for different fuel station brands.
    
        This enumeration lists various fuel station brands, including popular ones like 'Amic', 'BP', 
        'Moya', 'Total', and others. The enumeration is used in the `brand_name` field of the `StationPrices` model.
        """

        AMIC = "amic", "Amic"
        LOTOS = "lotos", "Lotos"
        LOTOS_OPTIMA = "lotos optima", "Lotos Optima"
        CIRCLE_K = "circle-k", "Circle-k"
        BP = "bp", "BP"
        MOYA = "moya", "Moya"
        AUCHAN = "auchan", "Auchan"
        TESCO = "tesco", "Tesco"
        CARREFOUR = "carrefour", "Carrefour"
        OLKOP = "olkop", "Olkop"
        LECLERC = "leclerc", "Leclerc"
        INTERMARCHE = "intermarche", "Intermarche"
        MOL = "mol", "MOL"
        HUZAR = "huzar", "Huzar"
        TOTAL = "total", "Total"
        POLSKA = "polska", "Polska"

    brand_name = models.CharField(
        max_length=20,
        choices=BrandChoices.choices,
        help_text="Select the fuel station brand."
    )
    currency = models.CharField(
        max_length=3,
        default="PLN",
        help_text="The currency of the purchase price."
    )
    diesel_price = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        help_text="Price per liter of Diesel in PLN",
        null=True
    )
    lpg_price = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        help_text="Price per liter of LPG in PLN",
        null=True
    )
    pb95_price = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        help_text="Price per liter of BP95 in PLN",
        null=True
    )
    pb98_price = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        help_text="Price per liter of BP98 in PLN",
        null=True
    )
    updated_at = models.DateTimeField(auto_now=True)


class Station(models.Model):
    """
    Model representing a fuel station, including its geographic location and associated station prices.
    
    This model includes an address, geographic location (using GIS for geographic data), and a 
    foreign key to the `StationPrices` model, which holds the fuel price details. The `location` 
    field uses Django's GIS `PointField` to store the geographical coordinates of the station.
    """

    address = models.CharField(max_length=100, null=True)
    location = gis_models.PointField(geography=True)
    station_prices = models.ForeignKey(
        StationPrices,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="stations"
    )

cheapdrive_web/entry/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.mail import send_mail


User = get_user_model()

class UserRegistrationForm(forms.ModelForm):
    """
    Form for registering a new user with password confirmation.
    
    The form includes fields for the user's username, email, and password. 
    It also includes a second password field to confirm that both passwords match. 
    When the form is valid, it hashes the password and saves the user to the database.
    """

    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("username", "email")
        help_texts = {"username": None, "email": None}

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password2 = cleaned_data.get("password2")
        if password != password2:
            raise forms.ValidationError("Passwords do not match")
        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

cheapdrive_web/entry/views.py
from turtle import update
from django.http import HttpRequest, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from refill.models import Trip
from .forms import UserRegistrationForm  
from api_calls.other_api_calls import get_address_from_coords
import logging
from refill.calculate_consumption import calculate_form_fuel_consumption

logger = logging.getLogger("my_logger")

def register(request: HttpRequest) -> HttpResponse:
    """
    Handles user registration by displaying the registration form, validating 
    the input data, and saving a new user to the database. After successful 
    registration, the user is redirected to the login page.
    
    Args:
        request (HttpRequest): The HTTP request object.
    
    Returns:
        HttpResponse: The rendered registration form or a redirect to the login page.
    """
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()  # Create and save the user
            messages.success(request, 'Registration successful!')
            return redirect('entry:login')
        messages.error(request, 'Invalid registration information.')
    else:
        form = UserRegistrationForm()
    return render(request, 'entry/register.html', {'form': form})

def visit(request: HttpRequest) -> HttpResponse:
    """
    Renders the 'visit' page.

    Args:
        request (HttpRequest): The HTTP request object.
    
    Returns:
        HttpResponse: The rendered visit page.
    """
    return render(request, 'entry/visit.html')

def login_view(request: HttpRequest) -> HttpResponse:
    """
    Handles user authentication and login. If the user is authenticated, 
    they are redirected to the logged-in view. If not, an authentication form 
    is displayed, and the credentials are validated. Upon successful login, 
    the user is redirected to the next page.
    
    Args:
        request (HttpRequest): The HTTP request object.
    
    Returns:
        HttpResponse: The rendered login page or a redirect to the logged-in page.
    """
    if request.user.is_authenticated:
        return redirect('entry:logout')  
    
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username: str = form.cleaned_data['username']
            password: str = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, 'Login successful!')
                next_url = request.GET.get('next', 'entry:logged')
                return redirect(next_url)
            messages.error(request, 'Invalid username or password.')
        else:
            messages.error(request, 'Invalid form data.')
    else:
        form = AuthenticationForm()
        if 'next' in request.GET:
            messages.error(request, 'You must be logged in to access that page.')
    
    response = render(request, 'entry/login.html', {'form': form})
    response['Cache-Control'] = 'no-cache, no-store, must-revalidate'
    response['Pragma'] = 'no-cache'
    response['Expires'] = '0'
    return response

def logout_view(request: HttpRequest) -> HttpResponse:
    """
    Logs out the user and redirects them to the visit page with a success message.
    
    Args:
        request (HttpRequest): The HTTP request object.
    
    Returns:
        HttpResponse: A redirect to the visit page after logging out.
    """
    logout(request)
    messages.success(request, 'You have been logged out successfully.')
    return redirect('entry:visit')

def guest_access(request: HttpRequest) -> HttpResponse:
    """
    Grants guest access by setting a session flag and redirects to a guest 
    data loading page.
    
    Args:
        request (HttpRequest): The HTTP request object.
    
    Returns:
        HttpResponse: A redirect to the guest data page.
    """
    request.session['is_guest'] = True
    return redirect(f"{reverse('refill:load_data')}?vehicle_id=none&trip_id=none")

@login_required(login_url='/login/')
def logged_view(request: HttpRequest) -> HttpResponse:
    """
    Handles user navigation after logging in. Displays options for history, 
    user vehicles, new trip creation, or logging out. Redirects based on user 
    action.
    
    Args:
        request (HttpRequest): The HTTP request object.
    
    Returns:
        HttpResponse: A redirect to the chosen action or the logged-in view.
    """
    if request.method == 'POST':
        action: str = request.POST.get('action', '')
        action_map = {
            'history': 'entry:trip_history',
            'user_vehicles': 'entry:user_vehicles',
            'new_trip': f"{reverse('refill:load_data')}?vehicle_id=none&trip_id=none",
            'logout': 'entry:logout'
        }
        
        if action in action_map:
            return redirect(action_map[action])
        
        messages.error(request, "Invalid action selected.")
    
    return render(request, 'entry/logged.html')

@login_required(login_url='/login/')
def trip_history_view(request: HttpRequest) -> HttpResponse:
    """
    Displays the trip history for the logged-in user. It retrieves trips from 
    the database and renders them with information such as distance, duration, 
    and price.
    
    Args:
        request (HttpRequest): The HTTP request object.
    
    Returns:
        HttpResponse: The rendered trip history page.
    """
    trips = Trip.objects.filter(user=request.user).order_by('-first_trip_node_id')
    
    trip_data = [
        {
            'origin_address': trip.origin_address,
            'destination_address': trip.destination_address,
            'total_distance': trip.total_distance(),
            'total_duration': trip.total_duration(),
            'total_price': trip.total_price_bought_and_used()[1],
            'currency': trip.main_currency(),
            'trip_id': trip.id,
        }
        for trip in trips
    ]
    
    return render(request, 'entry/trip_history.html', {'trip_data': trip_data})

@login_required(login_url='/login/')
def user_vehicles_view(request: HttpRequest) -> HttpResponse:
    """
    Displays the vehicles owned by the logged-in user, including information 
    such as tank size, fuel type, and fuel consumption. 
    
    Args:
        request (HttpRequest): The HTTP request object.
    
    Returns:
        HttpResponse: The rendered user vehicles page.
    """
    vehicles = request.user.vehicle_data.all()
    vehicle_data = [
        {
            'tank_size': vehicle.tank_size,
            'fuel_type': vehicle.fuel_type,
            'form_fuel_consumption': calculate_form_fuel_consumption(vehicle.driving_conditions, vehicle.fuel_consumption_per_100km),
            'driving_conditions': str(vehicle.driving_conditions).capitalize(),
            'id': vehicle.id
        }
        for vehicle in vehicles
    ]
    return render(request, 'entry/user_vehicles.html', {'vehicle_data': vehicle_data})

cheapdrive_web/templates/entry/logged.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Logged Options</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'entry/logged.css' %}">

</head>
<body>
    <h1>Welcome to the Trip Manager</h1>
    <p>What would you like to do?</p>
    <div class="form-container">
        <form method="post">
            {% csrf_token %}

            <button type="submit" name="action" value="new_trip">Set Up a New Trip</button>
            <button type="submit" name="action" value="history">View Trip History</button>
            <button type="submit" name="action" value="user_vehicles">View Your Vehicles</button>


            <button type="submit" name="action" value="logout">Log Out</button>
        </form>
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li class="{{ message.tags }}">{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    
</body>
</html>

cheapdrive_web/templates/entry/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'entry/login_register.css' %}">

</head>
<body>
    <form method="post" action="{% url 'entry:login' %}" class="login-form">

        {% csrf_token %}

        {{ form.as_p }}  <!-- Django renders the form fields -->
        <button type="submit">Login</button>
    </form>
    <p>Don't have an account? <a href="{% url 'entry:register' %}" class="register-link">Register here</a>.</p>
    <a href="{% url 'entry:guest_access' %}" class="guest-link">Continue as Guest</a>

    <div class="messages">
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li class="{% if message.tags %} {{ message.tags }}{% endif %}">{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</body>
</html>

cheapdrive_web/templates/entry/register.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'entry/login_register.css' %}">
</head>
<body>
    <form method="post" action="{% url 'entry:register' %}" class="register-form">
        {% csrf_token %}
        {{ form.as_p }}  <!-- Django renders the form fields -->
        <button type="submit">Register</button>
    </form>

    <div class="messages">
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li class="{% if message.tags %} {{ message.tags }}{% endif %}">{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</body>
</html>

cheapdrive_web/templates/entry/trip_history.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Trip History</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'entry/trip_history.css' %}">
</head>
<body>
    <div class="container">
        <h1>Trip History</h1>

        {% if trip_data %}
        <table class="table">
            <thead>
                <tr>
                    <th>Starting Address</th>
                    <th>Finishing Address</th>
                    <th>Distance (km)</th>
                    <th>Duration (min)</th>
                    <th>Trip Price</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for trip_entry in trip_data %}
                <tr>
                    <td>{{ trip_entry.origin_address }}</td>
                    <td>{{ trip_entry.destination_address }}</td>
                    <td>{{ trip_entry.total_distance }}</td>
                    <td>{{ trip_entry.total_duration }}</td>

                    <td>{{ trip_entry.total_price }} {{ trip_entry.currency }}</td>
                    <td class="action-btns">
                        <a href="{% url 'refill:load_data' %}?vehicle_id=none&trip_id={{ trip_entry.trip_id }}" class="btn btn-action">
                            Use Addresses
                        </a>
                    </td>
                    {% endfor %}
                </tr>
            </tbody>
        </table>
        {% else %}
        <p>No trip history found.</p>
        {% endif %}
    </div>
</body>
</html>

cheapdrive_web/templates/entry/user_vehicles.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vehicle History</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'entry/trip_history.css' %}">
</head>
<body>
    <div class="container">
        <h1>Vehicle History</h1>

        {% if vehicle_data %}
        <table class="table">
            <thead>
                <tr>
                    <th>Fuel Type</th>
                    <th>Tank Size (L)</th>
                    <th>Fuel Consumption (L/100km)</th>
                    <th>Driving Condition</th>
                </tr>
            </thead>
            <tbody>
                {% for vehicle_entry in vehicle_data %}
                <tr>
                    <td>{{ vehicle_entry.fuel_type }}</td>
                    <td>{{ vehicle_entry.tank_size }}</td>
                    <td>{{ vehicle_entry.form_fuel_consumption }}</td>
                    <td>{{ vehicle_entry.driving_conditions }}</td>

                    <td class="action-btns">
                        <a href="{% url 'refill:load_data' %}?vehicle_id={{vehicle_entry.id}}&trip_id=none" class="btn btn-action">
                            Use Vehicle
                        </a>
                    </td>
                    {% endfor %}
                </tr>
            </tbody>
        </table>
        {% else %}
        <p>No vehicle history found.</p>
        {% endif %}
    </div>
</body>
</html>

cheapdrive_web/templates/entry/visit.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Road Trip Help</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'entry/visit.css' %}">
</head>
<body>
    <p>Hello dear user!!! I assume You would like to get some help in the road trip department. Thankfully, Cheapdrive is here with you.</p>
    <div class="button-container">
        <a href="{% url 'entry:login' %}"><button>Let's get going</button></a>
    </div>
</body>
</html>